export default {
  login: "john-smilga",
  id: 42133389,
  node_id: "MDQ6VXNlcjQyMTMzMzg5",
  avatar_url: "https://avatars3.githubusercontent.com/u/42133389?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/john-smilga",
  html_url: "https://github.com/john-smilga",
  followers_url: "https://api.github.com/users/john-smilga/followers",
  following_url:
    "https://api.github.com/users/john-smilga/following{/other_user}",
  gists_url: "https://api.github.com/users/john-smilga/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/john-smilga/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/john-smilga/subscriptions",
  organizations_url: "https://api.github.com/users/john-smilga/orgs",
  repos_url: "https://api.github.com/users/john-smilga/repos",
  events_url: "https://api.github.com/users/john-smilga/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/john-smilga/received_events",
  type: "User",
  site_admin: false,
  name: "John Smilga",
  company: "Coding Addict",
  blog: "www.johnsmilga.com",
  location: "Los Angeles",
  email: null,
  hireable: null,
  bio: "Creator of Coding Addict",
  twitter_username: "john_smilga",
  public_repos: 152,
  public_gists: 0,
  followers: 1495,
  following: 0,
  created_at: "2018-08-06T06:48:23Z",
  updated_at: "2020-07-08T05:01:32Z",
};

// {
//   login: "anst9000",
//   id: 40022844,
//   node_id: "MDQ6VXNlcjQwMDIyODQ0",
//   avatar_url: "https://avatars1.githubusercontent.com/u/40022844?v=4",
//   gravatar_id: "",
//   url: "https://api.github.com/users/anst9000",
//   html_url: "https://github.com/anst9000",
//   followers_url: "https://api.github.com/users/anst9000/followers",
//   following_url: "https://api.github.com/users/anst9000/following{/other_user}",
//   gists_url: "https://api.github.com/users/anst9000/gists{/gist_id}",
//   starred_url: "https://api.github.com/users/anst9000/starred{/owner}{/repo}",
//   subscriptions_url: "https://api.github.com/users/anst9000/subscriptions",
//   organizations_url: "https://api.github.com/users/anst9000/orgs",
//   repos_url: "https://api.github.com/users/anst9000/repos",
//   events_url: "https://api.github.com/users/anst9000/events{/privacy}",
//   received_events_url: "https://api.github.com/users/anst9000/received_events",
//   type: "User",
//   site_admin: false,
//   name: "Anders Strömberg",
//   company: "@mention Mid Sweden University",
//   blog: "",
//   location: "Sundsvall, Sweden",
//   email: null,
//   hireable: true,
//   bio: null,
//   twitter_username: null,
//   public_repos: 59,
//   public_gists: 0,
//   followers: 0,
//   following: 0,
//   created_at: "2018-06-07T08:54:25Z",
//   updated_at: "2020-09-23T11:47:33Z",
// };
